// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Action    string
	IpAddress string
	UserAgent string
	CreatedAt pgtype.Timestamptz
}

type Bid struct {
	ID                     pgtype.UUID
	TenderID               pgtype.UUID
	TalentID               pgtype.UUID
	CoverLetter            string
	BidAmount              int64
	EstimatedDurationHours pgtype.Int4
	DpPercentage           pgtype.Int4
	MaxRevisions           pgtype.Int4
	PortfolioIds           []pgtype.UUID
	Status                 pgtype.Text
	CreatedAt              pgtype.Timestamptz
}

type Category struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	ParentID  pgtype.UUID
	IconUrl   pgtype.Text
	SortOrder pgtype.Int4
	IsActive  pgtype.Bool
}

type ChatMessage struct {
	ID          pgtype.UUID
	RoomID      pgtype.UUID
	SenderID    pgtype.UUID
	MessageType pgtype.Text
	Content     pgtype.Text
	MediaUrl    pgtype.Text
	Metadata    []byte
	IsRead      pgtype.Bool
	CreatedAt   pgtype.Timestamptz
}

type ChatRoom struct {
	ID            pgtype.UUID
	Type          string
	OrderID       pgtype.UUID
	TenderID      pgtype.UUID
	BidID         pgtype.UUID
	UserID        pgtype.UUID
	TalentID      pgtype.UUID
	LastMessageAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type Contract struct {
	ID                  pgtype.UUID
	ContractNumber      string
	OrderID             pgtype.UUID
	UserID              pgtype.UUID
	TalentID            pgtype.UUID
	WorkTitle           string
	WorkDescription     string
	WorkStartDate       pgtype.Date
	WorkEndDate         pgtype.Date
	Location            pgtype.Text
	TotalAmount         int64
	DpPercentage        int32
	DpAmount            int64
	MaxRevisions        pgtype.Int4
	CancellationTerms   pgtype.Text
	UserSignedAt        pgtype.Timestamptz
	TalentSignedAt      pgtype.Timestamptz
	UserSignatureHash   pgtype.Text
	TalentSignatureHash pgtype.Text
	DocumentHash        pgtype.Text
	PdfUrl              pgtype.Text
	Status              pgtype.Text
	CreatedAt           pgtype.Timestamptz
}

type Disbursement struct {
	ID                pgtype.UUID
	OrderID           pgtype.UUID
	TalentID          pgtype.UUID
	Amount            int64
	BankCode          pgtype.Text
	BankAccount       pgtype.Text
	AccountName       pgtype.Text
	ExternalReference pgtype.Text
	Status            pgtype.Text
	DisbursedAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type Dispute struct {
	ID                     pgtype.UUID
	OrderID                pgtype.UUID
	FiledBy                pgtype.UUID
	ReasonCategory         string
	Description            string
	EvidenceUrls           []string
	RespondentResponse     pgtype.Text
	RespondentEvidenceUrls []string
	AdminNotes             pgtype.Text
	Decision               pgtype.Text
	SplitUserPercentage    pgtype.Int4
	ResolvedAt             pgtype.Timestamptz
	ResolvedBy             pgtype.UUID
	Status                 pgtype.Text
	CreatedAt              pgtype.Timestamptz
}

type Notification struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Type      string
	Title     string
	Body      string
	ActionUrl pgtype.Text
	Metadata  []byte
	IsRead    pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type Order struct {
	ID                  pgtype.UUID
	OrderNumber         string
	UserID              pgtype.UUID
	TalentID            pgtype.UUID
	ListingID           pgtype.UUID
	PackageID           pgtype.UUID
	TenderID            pgtype.UUID
	BidID               pgtype.UUID
	Title               string
	Description         pgtype.Text
	WorkDateStart       pgtype.Date
	WorkDateEnd         pgtype.Date
	LocationAddress     pgtype.Text
	FinalAmount         int64
	DpAmount            int64
	RemainingAmount     int64
	PlatformFee         int64
	TalentReceiveAmount int64
	Status              pgtype.Text
	ProgressPercentage  pgtype.Int4
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type Payment struct {
	ID                    pgtype.UUID
	OrderID               pgtype.UUID
	PaymentType           string
	Amount                int64
	Method                string
	Provider              pgtype.Text
	ExternalTransactionID pgtype.Text
	Status                pgtype.Text
	PaidAt                pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}

type Review struct {
	ID                  pgtype.UUID
	OrderID             pgtype.UUID
	ReviewerID          pgtype.UUID
	RevieweeID          pgtype.UUID
	ReviewType          string
	RatingOverall       pgtype.Numeric
	RatingQuality       pgtype.Numeric
	RatingTimeliness    pgtype.Numeric
	RatingCommunication pgtype.Numeric
	RatingFriendliness  pgtype.Numeric
	RatingValue         pgtype.Numeric
	Comment             pgtype.Text
	PhotoUrls           []string
	WouldRecommend      pgtype.Bool
	TalentResponse      pgtype.Text
	TalentRespondedAt   pgtype.Timestamptz
	IsFlagged           pgtype.Bool
	IsPublished         pgtype.Bool
	CreatedAt           pgtype.Timestamptz
}

type ServiceListing struct {
	ID            pgtype.UUID
	TalentID      pgtype.UUID
	CategoryID    pgtype.UUID
	Title         string
	Description   string
	Tags          []string
	CoverImageUrl pgtype.Text
	GalleryUrls   []string
	VideoUrls     []string
	Status        pgtype.Text
	ViewCount     pgtype.Int4
	BookingCount  pgtype.Int4
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ServicePackage struct {
	ID            pgtype.UUID
	ListingID     pgtype.UUID
	Name          string
	Description   pgtype.Text
	PriceAmount   int64
	PriceType     pgtype.Text
	DurationHours pgtype.Int4
	Inclusions    []string
	MaxRevisions  pgtype.Int4
	SortOrder     pgtype.Int4
}

type TalentProfile struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	Bio                   pgtype.Text
	Tagline               pgtype.Text
	YearsExperience       pgtype.Int4
	ServiceRadiusKm       pgtype.Int4
	Location              interface{}
	IsKycVerified         pgtype.Bool
	KycDocumentUrl        pgtype.Text
	KycSelfieUrl          pgtype.Text
	KycReviewedAt         pgtype.Timestamptz
	KycReviewedBy         pgtype.UUID
	SubscriptionTier      pgtype.Text
	SubscriptionExpiresAt pgtype.Timestamptz
	AverageRating         pgtype.Numeric
	TotalReviews          pgtype.Int4
	TotalCompletedJobs    pgtype.Int4
	ResponseTimeHours     pgtype.Int4
	CreatedAt             pgtype.Timestamptz
}

type Tender struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	CategoryID         pgtype.UUID
	Title              string
	Description        string
	ReferenceMediaUrls []string
	LocationAddress    pgtype.Text
	LocationLat        pgtype.Numeric
	LocationLng        pgtype.Numeric
	WorkDateStart      pgtype.Date
	WorkDateEnd        pgtype.Date
	BudgetMin          pgtype.Int8
	BudgetMax          pgtype.Int8
	BudgetIsNegotiable pgtype.Bool
	IsUrgent           pgtype.Bool
	MinExperienceYears pgtype.Int4
	MinRating          pgtype.Numeric
	RequireVerified    pgtype.Bool
	PreferTeam         pgtype.Bool
	MaxBids            pgtype.Int4
	ExpiresAt          pgtype.Timestamptz
	Status             pgtype.Text
	SelectedBidID      pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        pgtype.Text
	Phone        string
	PasswordHash pgtype.Text
	FullName     string
	Role         string
	AvatarUrl    pgtype.Text
	City         pgtype.Text
	IsVerified   pgtype.Bool
	IsActive     pgtype.Bool
	GoogleID     pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
