// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_logs (
  id, user_id, action, ip_address, user_agent
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, user_id, action, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Action    string
	IpAddress string
	UserAgent string
}

// ==========================================
// AUTHENTICATION & AUDIT QUERIES
// ==========================================
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (
  id, name, slug, parent_id, icon_url, sort_order, is_active
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, slug, parent_id, icon_url, sort_order, is_active
`

type CreateCategoryParams struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	ParentID  pgtype.UUID
	IconUrl   pgtype.Text
	SortOrder pgtype.Int4
	IsActive  pgtype.Bool
}

// ==========================================
// CATEGORIES QUERIES
// ==========================================
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.IconUrl,
		arg.SortOrder,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.IconUrl,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (
  id, order_number, user_id, talent_id, listing_id, package_id, tender_id, bid_id, title, description, work_date_start, work_date_end, location_address, final_amount, dp_amount, remaining_amount, platform_fee, talent_receive_amount, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
RETURNING id, order_number, user_id, talent_id, listing_id, package_id, tender_id, bid_id, title, description, work_date_start, work_date_end, location_address, final_amount, dp_amount, remaining_amount, platform_fee, talent_receive_amount, status, progress_percentage, created_at, updated_at
`

type CreateOrderParams struct {
	ID                  pgtype.UUID
	OrderNumber         string
	UserID              pgtype.UUID
	TalentID            pgtype.UUID
	ListingID           pgtype.UUID
	PackageID           pgtype.UUID
	TenderID            pgtype.UUID
	BidID               pgtype.UUID
	Title               string
	Description         pgtype.Text
	WorkDateStart       pgtype.Date
	WorkDateEnd         pgtype.Date
	LocationAddress     pgtype.Text
	FinalAmount         int64
	DpAmount            int64
	RemainingAmount     int64
	PlatformFee         int64
	TalentReceiveAmount int64
	Status              pgtype.Text
}

// ==========================================
// ORDERS QUERIES
// ==========================================
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.OrderNumber,
		arg.UserID,
		arg.TalentID,
		arg.ListingID,
		arg.PackageID,
		arg.TenderID,
		arg.BidID,
		arg.Title,
		arg.Description,
		arg.WorkDateStart,
		arg.WorkDateEnd,
		arg.LocationAddress,
		arg.FinalAmount,
		arg.DpAmount,
		arg.RemainingAmount,
		arg.PlatformFee,
		arg.TalentReceiveAmount,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.TalentID,
		&i.ListingID,
		&i.PackageID,
		&i.TenderID,
		&i.BidID,
		&i.Title,
		&i.Description,
		&i.WorkDateStart,
		&i.WorkDateEnd,
		&i.LocationAddress,
		&i.FinalAmount,
		&i.DpAmount,
		&i.RemainingAmount,
		&i.PlatformFee,
		&i.TalentReceiveAmount,
		&i.Status,
		&i.ProgressPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceListing = `-- name: CreateServiceListing :one

INSERT INTO service_listings (
  id, talent_id, category_id, title, description, tags, cover_image_url, gallery_urls, video_urls, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, talent_id, category_id, title, description, tags, cover_image_url, gallery_urls, video_urls, status, view_count, booking_count, created_at, updated_at
`

type CreateServiceListingParams struct {
	ID            pgtype.UUID
	TalentID      pgtype.UUID
	CategoryID    pgtype.UUID
	Title         string
	Description   string
	Tags          []string
	CoverImageUrl pgtype.Text
	GalleryUrls   []string
	VideoUrls     []string
	Status        pgtype.Text
}

// ==========================================
// SERVICE LISTINGS QUERIES
// ==========================================
func (q *Queries) CreateServiceListing(ctx context.Context, arg CreateServiceListingParams) (ServiceListing, error) {
	row := q.db.QueryRow(ctx, createServiceListing,
		arg.ID,
		arg.TalentID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.CoverImageUrl,
		arg.GalleryUrls,
		arg.VideoUrls,
		arg.Status,
	)
	var i ServiceListing
	err := row.Scan(
		&i.ID,
		&i.TalentID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.CoverImageUrl,
		&i.GalleryUrls,
		&i.VideoUrls,
		&i.Status,
		&i.ViewCount,
		&i.BookingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServicePackage = `-- name: CreateServicePackage :one

INSERT INTO service_packages (
  id, listing_id, name, description, price_amount, price_type, duration_hours, inclusions, max_revisions, sort_order
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, listing_id, name, description, price_amount, price_type, duration_hours, inclusions, max_revisions, sort_order
`

type CreateServicePackageParams struct {
	ID            pgtype.UUID
	ListingID     pgtype.UUID
	Name          string
	Description   pgtype.Text
	PriceAmount   int64
	PriceType     pgtype.Text
	DurationHours pgtype.Int4
	Inclusions    []string
	MaxRevisions  pgtype.Int4
	SortOrder     pgtype.Int4
}

// ==========================================
// SERVICE PACKAGES QUERIES
// ==========================================
func (q *Queries) CreateServicePackage(ctx context.Context, arg CreateServicePackageParams) (ServicePackage, error) {
	row := q.db.QueryRow(ctx, createServicePackage,
		arg.ID,
		arg.ListingID,
		arg.Name,
		arg.Description,
		arg.PriceAmount,
		arg.PriceType,
		arg.DurationHours,
		arg.Inclusions,
		arg.MaxRevisions,
		arg.SortOrder,
	)
	var i ServicePackage
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.Name,
		&i.Description,
		&i.PriceAmount,
		&i.PriceType,
		&i.DurationHours,
		&i.Inclusions,
		&i.MaxRevisions,
		&i.SortOrder,
	)
	return i, err
}

const createTalentProfile = `-- name: CreateTalentProfile :one

INSERT INTO talent_profiles (
  id, user_id, bio, tagline, years_experience, service_radius_km, location, is_kyc_verified, kyc_document_url, kyc_selfie_url, subscription_tier, average_rating
) VALUES (
  $1, $2, $3, $4, $5, $6, ST_SetSRID(ST_MakePoint(cast($7 as float8), cast($8 as float8)), 4326)::geography, $9, $10, $11, $12, $13
)
RETURNING id, user_id, bio, tagline, years_experience, service_radius_km, location, is_kyc_verified, kyc_document_url, kyc_selfie_url, kyc_reviewed_at, kyc_reviewed_by, subscription_tier, subscription_expires_at, average_rating, total_reviews, total_completed_jobs, response_time_hours, created_at
`

type CreateTalentProfileParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Bio              pgtype.Text
	Tagline          pgtype.Text
	YearsExperience  pgtype.Int4
	ServiceRadiusKm  pgtype.Int4
	Longitude        float64
	Latitude         float64
	IsKycVerified    pgtype.Bool
	KycDocumentUrl   pgtype.Text
	KycSelfieUrl     pgtype.Text
	SubscriptionTier pgtype.Text
	AverageRating    pgtype.Numeric
}

// ==========================================
// TALENT PROFILES QUERIES
// ==========================================
func (q *Queries) CreateTalentProfile(ctx context.Context, arg CreateTalentProfileParams) (TalentProfile, error) {
	row := q.db.QueryRow(ctx, createTalentProfile,
		arg.ID,
		arg.UserID,
		arg.Bio,
		arg.Tagline,
		arg.YearsExperience,
		arg.ServiceRadiusKm,
		arg.Longitude,
		arg.Latitude,
		arg.IsKycVerified,
		arg.KycDocumentUrl,
		arg.KycSelfieUrl,
		arg.SubscriptionTier,
		arg.AverageRating,
	)
	var i TalentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.Tagline,
		&i.YearsExperience,
		&i.ServiceRadiusKm,
		&i.Location,
		&i.IsKycVerified,
		&i.KycDocumentUrl,
		&i.KycSelfieUrl,
		&i.KycReviewedAt,
		&i.KycReviewedBy,
		&i.SubscriptionTier,
		&i.SubscriptionExpiresAt,
		&i.AverageRating,
		&i.TotalReviews,
		&i.TotalCompletedJobs,
		&i.ResponseTimeHours,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
  id, email, phone, password_hash, full_name, role, avatar_url, city, is_verified, is_active, google_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, email, phone, password_hash, full_name, role, avatar_url, city, is_verified, is_active, google_id, created_at, updated_at
`

type CreateUserParams struct {
	ID           pgtype.UUID
	Email        pgtype.Text
	Phone        string
	PasswordHash pgtype.Text
	FullName     string
	Role         string
	AvatarUrl    pgtype.Text
	City         pgtype.Text
	IsVerified   pgtype.Bool
	IsActive     pgtype.Bool
	GoogleID     pgtype.Text
}

// ==========================================
// USERS QUERIES
// ==========================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.AvatarUrl,
		arg.City,
		arg.IsVerified,
		arg.IsActive,
		arg.GoogleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.City,
		&i.IsVerified,
		&i.IsActive,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, order_number, user_id, talent_id, listing_id, package_id, tender_id, bid_id, title, description, work_date_start, work_date_end, location_address, final_amount, dp_amount, remaining_amount, platform_fee, talent_receive_amount, status, progress_percentage, created_at, updated_at FROM orders WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.UserID,
		&i.TalentID,
		&i.ListingID,
		&i.PackageID,
		&i.TenderID,
		&i.BidID,
		&i.Title,
		&i.Description,
		&i.WorkDateStart,
		&i.WorkDateEnd,
		&i.LocationAddress,
		&i.FinalAmount,
		&i.DpAmount,
		&i.RemainingAmount,
		&i.PlatformFee,
		&i.TalentReceiveAmount,
		&i.Status,
		&i.ProgressPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByTalentID = `-- name: GetOrdersByTalentID :many
SELECT o.id, o.order_number, o.user_id, o.talent_id, o.listing_id, o.package_id, o.tender_id, o.bid_id, o.title, o.description, o.work_date_start, o.work_date_end, o.location_address, o.final_amount, o.dp_amount, o.remaining_amount, o.platform_fee, o.talent_receive_amount, o.status, o.progress_percentage, o.created_at, o.updated_at, u.full_name as user_name
FROM orders o
JOIN users u ON o.user_id = u.id
WHERE o.talent_id = $1
ORDER BY o.created_at DESC
`

type GetOrdersByTalentIDRow struct {
	ID                  pgtype.UUID
	OrderNumber         string
	UserID              pgtype.UUID
	TalentID            pgtype.UUID
	ListingID           pgtype.UUID
	PackageID           pgtype.UUID
	TenderID            pgtype.UUID
	BidID               pgtype.UUID
	Title               string
	Description         pgtype.Text
	WorkDateStart       pgtype.Date
	WorkDateEnd         pgtype.Date
	LocationAddress     pgtype.Text
	FinalAmount         int64
	DpAmount            int64
	RemainingAmount     int64
	PlatformFee         int64
	TalentReceiveAmount int64
	Status              pgtype.Text
	ProgressPercentage  pgtype.Int4
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	UserName            string
}

func (q *Queries) GetOrdersByTalentID(ctx context.Context, talentID pgtype.UUID) ([]GetOrdersByTalentIDRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByTalentID, talentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByTalentIDRow
	for rows.Next() {
		var i GetOrdersByTalentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.TalentID,
			&i.ListingID,
			&i.PackageID,
			&i.TenderID,
			&i.BidID,
			&i.Title,
			&i.Description,
			&i.WorkDateStart,
			&i.WorkDateEnd,
			&i.LocationAddress,
			&i.FinalAmount,
			&i.DpAmount,
			&i.RemainingAmount,
			&i.PlatformFee,
			&i.TalentReceiveAmount,
			&i.Status,
			&i.ProgressPercentage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT o.id, o.order_number, o.user_id, o.talent_id, o.listing_id, o.package_id, o.tender_id, o.bid_id, o.title, o.description, o.work_date_start, o.work_date_end, o.location_address, o.final_amount, o.dp_amount, o.remaining_amount, o.platform_fee, o.talent_receive_amount, o.status, o.progress_percentage, o.created_at, o.updated_at, u.full_name as talent_name
FROM orders o
JOIN talent_profiles tp ON o.talent_id = tp.id
JOIN users u ON tp.user_id = u.id
WHERE o.user_id = $1
ORDER BY o.created_at DESC
`

type GetOrdersByUserIDRow struct {
	ID                  pgtype.UUID
	OrderNumber         string
	UserID              pgtype.UUID
	TalentID            pgtype.UUID
	ListingID           pgtype.UUID
	PackageID           pgtype.UUID
	TenderID            pgtype.UUID
	BidID               pgtype.UUID
	Title               string
	Description         pgtype.Text
	WorkDateStart       pgtype.Date
	WorkDateEnd         pgtype.Date
	LocationAddress     pgtype.Text
	FinalAmount         int64
	DpAmount            int64
	RemainingAmount     int64
	PlatformFee         int64
	TalentReceiveAmount int64
	Status              pgtype.Text
	ProgressPercentage  pgtype.Int4
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	TalentName          string
}

func (q *Queries) GetOrdersByUserID(ctx context.Context, userID pgtype.UUID) ([]GetOrdersByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByUserIDRow
	for rows.Next() {
		var i GetOrdersByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.UserID,
			&i.TalentID,
			&i.ListingID,
			&i.PackageID,
			&i.TenderID,
			&i.BidID,
			&i.Title,
			&i.Description,
			&i.WorkDateStart,
			&i.WorkDateEnd,
			&i.LocationAddress,
			&i.FinalAmount,
			&i.DpAmount,
			&i.RemainingAmount,
			&i.PlatformFee,
			&i.TalentReceiveAmount,
			&i.Status,
			&i.ProgressPercentage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TalentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceListingsByTalent = `-- name: GetServiceListingsByTalent :many
SELECT id, talent_id, category_id, title, description, tags, cover_image_url, gallery_urls, video_urls, status, view_count, booking_count, created_at, updated_at FROM service_listings WHERE talent_id = $1 AND status != 'deleted' ORDER BY created_at DESC
`

func (q *Queries) GetServiceListingsByTalent(ctx context.Context, talentID pgtype.UUID) ([]ServiceListing, error) {
	rows, err := q.db.Query(ctx, getServiceListingsByTalent, talentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceListing
	for rows.Next() {
		var i ServiceListing
		if err := rows.Scan(
			&i.ID,
			&i.TalentID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CoverImageUrl,
			&i.GalleryUrls,
			&i.VideoUrls,
			&i.Status,
			&i.ViewCount,
			&i.BookingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServicePackagesByListing = `-- name: GetServicePackagesByListing :many
SELECT id, listing_id, name, description, price_amount, price_type, duration_hours, inclusions, max_revisions, sort_order FROM service_packages WHERE listing_id = $1 ORDER BY sort_order ASC
`

func (q *Queries) GetServicePackagesByListing(ctx context.Context, listingID pgtype.UUID) ([]ServicePackage, error) {
	rows, err := q.db.Query(ctx, getServicePackagesByListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServicePackage
	for rows.Next() {
		var i ServicePackage
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.Name,
			&i.Description,
			&i.PriceAmount,
			&i.PriceType,
			&i.DurationHours,
			&i.Inclusions,
			&i.MaxRevisions,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTalentProfileByID = `-- name: GetTalentProfileByID :one
SELECT id, user_id, bio, tagline, years_experience, service_radius_km, location, is_kyc_verified, kyc_document_url, kyc_selfie_url, kyc_reviewed_at, kyc_reviewed_by, subscription_tier, subscription_expires_at, average_rating, total_reviews, total_completed_jobs, response_time_hours, created_at FROM talent_profiles WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTalentProfileByID(ctx context.Context, id pgtype.UUID) (TalentProfile, error) {
	row := q.db.QueryRow(ctx, getTalentProfileByID, id)
	var i TalentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.Tagline,
		&i.YearsExperience,
		&i.ServiceRadiusKm,
		&i.Location,
		&i.IsKycVerified,
		&i.KycDocumentUrl,
		&i.KycSelfieUrl,
		&i.KycReviewedAt,
		&i.KycReviewedBy,
		&i.SubscriptionTier,
		&i.SubscriptionExpiresAt,
		&i.AverageRating,
		&i.TotalReviews,
		&i.TotalCompletedJobs,
		&i.ResponseTimeHours,
		&i.CreatedAt,
	)
	return i, err
}

const getTalentProfileByUserID = `-- name: GetTalentProfileByUserID :one
SELECT id, user_id, bio, tagline, years_experience, service_radius_km, location, is_kyc_verified, kyc_document_url, kyc_selfie_url, kyc_reviewed_at, kyc_reviewed_by, subscription_tier, subscription_expires_at, average_rating, total_reviews, total_completed_jobs, response_time_hours, created_at FROM talent_profiles WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetTalentProfileByUserID(ctx context.Context, userID pgtype.UUID) (TalentProfile, error) {
	row := q.db.QueryRow(ctx, getTalentProfileByUserID, userID)
	var i TalentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.Tagline,
		&i.YearsExperience,
		&i.ServiceRadiusKm,
		&i.Location,
		&i.IsKycVerified,
		&i.KycDocumentUrl,
		&i.KycSelfieUrl,
		&i.KycReviewedAt,
		&i.KycReviewedBy,
		&i.SubscriptionTier,
		&i.SubscriptionExpiresAt,
		&i.AverageRating,
		&i.TotalReviews,
		&i.TotalCompletedJobs,
		&i.ResponseTimeHours,
		&i.CreatedAt,
	)
	return i, err
}

const getTalentProfilesInRadius = `-- name: GetTalentProfilesInRadius :many
SELECT 
  tp.id, tp.user_id, tp.bio, tp.tagline, tp.years_experience, tp.service_radius_km, tp.location, tp.is_kyc_verified, tp.kyc_document_url, tp.kyc_selfie_url, tp.kyc_reviewed_at, tp.kyc_reviewed_by, tp.subscription_tier, tp.subscription_expires_at, tp.average_rating, tp.total_reviews, tp.total_completed_jobs, tp.response_time_hours, tp.created_at, 
  u.full_name, 
  u.avatar_url, 
  ST_AsText(tp.location)::text as location_text,
  ST_Distance(tp.location, ST_SetSRID(ST_MakePoint(cast($1 as float8), cast($2 as float8)), 4326)::geography) as distance_meters
FROM talent_profiles tp
JOIN users u ON tp.user_id = u.id
WHERE ST_DWithin(
  tp.location,
  ST_SetSRID(ST_MakePoint(cast($1 as float8), cast($2 as float8)), 4326)::geography,
  cast($3 as float8)
)
ORDER BY distance_meters ASC
`

type GetTalentProfilesInRadiusParams struct {
	Longitude    float64
	Latitude     float64
	RadiusMeters float64
}

type GetTalentProfilesInRadiusRow struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	Bio                   pgtype.Text
	Tagline               pgtype.Text
	YearsExperience       pgtype.Int4
	ServiceRadiusKm       pgtype.Int4
	Location              interface{}
	IsKycVerified         pgtype.Bool
	KycDocumentUrl        pgtype.Text
	KycSelfieUrl          pgtype.Text
	KycReviewedAt         pgtype.Timestamptz
	KycReviewedBy         pgtype.UUID
	SubscriptionTier      pgtype.Text
	SubscriptionExpiresAt pgtype.Timestamptz
	AverageRating         pgtype.Numeric
	TotalReviews          pgtype.Int4
	TotalCompletedJobs    pgtype.Int4
	ResponseTimeHours     pgtype.Int4
	CreatedAt             pgtype.Timestamptz
	FullName              string
	AvatarUrl             pgtype.Text
	LocationText          string
	DistanceMeters        interface{}
}

// ST_DWithin works directly on geography points with distance in meters
func (q *Queries) GetTalentProfilesInRadius(ctx context.Context, arg GetTalentProfilesInRadiusParams) ([]GetTalentProfilesInRadiusRow, error) {
	rows, err := q.db.Query(ctx, getTalentProfilesInRadius, arg.Longitude, arg.Latitude, arg.RadiusMeters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTalentProfilesInRadiusRow
	for rows.Next() {
		var i GetTalentProfilesInRadiusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Bio,
			&i.Tagline,
			&i.YearsExperience,
			&i.ServiceRadiusKm,
			&i.Location,
			&i.IsKycVerified,
			&i.KycDocumentUrl,
			&i.KycSelfieUrl,
			&i.KycReviewedAt,
			&i.KycReviewedBy,
			&i.SubscriptionTier,
			&i.SubscriptionExpiresAt,
			&i.AverageRating,
			&i.TotalReviews,
			&i.TotalCompletedJobs,
			&i.ResponseTimeHours,
			&i.CreatedAt,
			&i.FullName,
			&i.AvatarUrl,
			&i.LocationText,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, password_hash, full_name, role, avatar_url, city, is_verified, is_active, google_id, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.City,
		&i.IsVerified,
		&i.IsActive,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, phone, password_hash, full_name, role, avatar_url, city, is_verified, is_active, google_id, created_at, updated_at FROM users WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.City,
		&i.IsVerified,
		&i.IsActive,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, password_hash, full_name, role, avatar_url, city, is_verified, is_active, google_id, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.City,
		&i.IsVerified,
		&i.IsActive,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, email, phone, password_hash, full_name, role, avatar_url, city, is_verified, is_active, google_id, created_at, updated_at FROM users WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.City,
		&i.IsVerified,
		&i.IsActive,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveServiceListings = `-- name: ListActiveServiceListings :many
SELECT 
  sl.id, sl.talent_id, sl.category_id, sl.title, sl.description, sl.tags, sl.cover_image_url, sl.gallery_urls, sl.video_urls, sl.status, sl.view_count, sl.booking_count, sl.created_at, sl.updated_at, 
  tp.average_rating, 
  tp.total_reviews, 
  u.full_name as talent_name,
  u.city as talent_city
FROM service_listings sl
JOIN talent_profiles tp ON sl.talent_id = tp.id
JOIN users u ON tp.user_id = u.id
WHERE sl.status = 'published' AND sl.category_id = $1
ORDER BY sl.created_at DESC
`

type ListActiveServiceListingsRow struct {
	ID            pgtype.UUID
	TalentID      pgtype.UUID
	CategoryID    pgtype.UUID
	Title         string
	Description   string
	Tags          []string
	CoverImageUrl pgtype.Text
	GalleryUrls   []string
	VideoUrls     []string
	Status        pgtype.Text
	ViewCount     pgtype.Int4
	BookingCount  pgtype.Int4
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	AverageRating pgtype.Numeric
	TotalReviews  pgtype.Int4
	TalentName    string
	TalentCity    pgtype.Text
}

func (q *Queries) ListActiveServiceListings(ctx context.Context, categoryID pgtype.UUID) ([]ListActiveServiceListingsRow, error) {
	rows, err := q.db.Query(ctx, listActiveServiceListings, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveServiceListingsRow
	for rows.Next() {
		var i ListActiveServiceListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.TalentID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CoverImageUrl,
			&i.GalleryUrls,
			&i.VideoUrls,
			&i.Status,
			&i.ViewCount,
			&i.BookingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AverageRating,
			&i.TotalReviews,
			&i.TalentName,
			&i.TalentCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, parent_id, icon_url, sort_order, is_active FROM categories WHERE parent_id IS NULL AND is_active = TRUE ORDER BY sort_order ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.IconUrl,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubCategories = `-- name: ListSubCategories :many
SELECT id, name, slug, parent_id, icon_url, sort_order, is_active FROM categories WHERE parent_id = $1 AND is_active = TRUE ORDER BY sort_order ASC
`

func (q *Queries) ListSubCategories(ctx context.Context, parentID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listSubCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.IconUrl,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserGoogleID = `-- name: UpdateUserGoogleID :one
UPDATE users 
SET google_id = $2, updated_at = NOW() 
WHERE id = $1 
RETURNING id, email, phone, password_hash, full_name, role, avatar_url, city, is_verified, is_active, google_id, created_at, updated_at
`

type UpdateUserGoogleIDParams struct {
	ID       pgtype.UUID
	GoogleID pgtype.Text
}

func (q *Queries) UpdateUserGoogleID(ctx context.Context, arg UpdateUserGoogleIDParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserGoogleID, arg.ID, arg.GoogleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.City,
		&i.IsVerified,
		&i.IsActive,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users 
SET password_hash = $2, updated_at = NOW() 
WHERE id = $1 
RETURNING id, email, phone, password_hash, full_name, role, avatar_url, city, is_verified, is_active, google_id, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash pgtype.Text
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.City,
		&i.IsVerified,
		&i.IsActive,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserVerificationStatus = `-- name: UpdateUserVerificationStatus :one
UPDATE users 
SET is_verified = $2, updated_at = NOW() 
WHERE id = $1 
RETURNING id, email, phone, password_hash, full_name, role, avatar_url, city, is_verified, is_active, google_id, created_at, updated_at
`

type UpdateUserVerificationStatusParams struct {
	ID         pgtype.UUID
	IsVerified pgtype.Bool
}

func (q *Queries) UpdateUserVerificationStatus(ctx context.Context, arg UpdateUserVerificationStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserVerificationStatus, arg.ID, arg.IsVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.AvatarUrl,
		&i.City,
		&i.IsVerified,
		&i.IsActive,
		&i.GoogleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
